### ISSUE TITLE
Elite Dangerous profile does not work

### ISSUE THREAD

**Issue by KaHonu** [DrParanoia/Aurora#11] opened 2019-11-23 18:59 UTC
### Expected Behaviour
Elite Dangerous profile should trigger lighting effects on RGB devices

### Actual Behaviour
No lighting effects at all -- the same error is logged in the Aurora log file continuously.

### Reproduction steps
Perform a clean install of RGB device software and configure. Clean install Aurora and configure. Even clicking on the Elite Dangerous profile in Aurora triggers the error in the log file.

### Frequency
I had the Elite profile working initially, but now it does not work at all.

### Aurora Version:
v0.6.4b-2

### Previously an Issue?
N/A

### Additional Notes:
When I first tried the fork of Aurora that has the Elite Dangerous profile it worked perfectly. I was testing out a newer version of Aurora for a while but wanted to go back to this release for Elite lighting effects. I think it may have even worked once after downgrading but I don't recall the timing of my uninstalls / re-installs.

Even if I completely 'clean' all Aurora, Logitech, and Corsair software I can't seem to get it to work any more. I have also re-installed MS Visual C++ 2017 redistributables (x86 and x64).

Devices are Logitech G903 and G910 keyboard with Logitech Gaming Software installed. I also tried a Corsair Strafe RGB and G903 with LGS and iCUE installed.

This is my cleanup script for when I want to start out with cleaned up installations:

reg delete HKEY_CURRENT_USER\Software\Corsair /f
reg delete HKEY_CURRENT_USER\Software\Logitech /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Corsair /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Corsair /f
rmdir /s/q C:\ProgramData\LogiShrd
rmdir /s/q C:\Users\Derek\AppData\Local\Logitech
rmdir /s/q C:\Users\Derek\AppData\Roaming\Logishrd
rmdir /s/q C:\Users\Derek\AppData\Roaming\Logitech
rmdir /s/q C:\Users\Derek\AppData\Roaming\Aurora
rmdir /s/q "C:\Program Files\Aurora"

The only setting I can't seem to find in a folder or the registry is the startup delay for Aurora. It seems to be retained even after a cleanup.

Finally, here is the error that is logged when I select the Elite profile in Aurora or when I play the game:

[ERROR] 13:57:45: ProfilesManager.Update() Exception, System.NullReferenceException: Object reference not set to an instance of an object.
   at Aurora.Profiles.EliteDangerous.Layers.EliteDangerousKeyBindsLayerHandler.Render(IGameState state) in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\EliteDangerous\Layers\EliteDangerousKeyBindsLayerHandler.cs:line 355
   at Aurora.Settings.Layers.Layer.Render(IGameState gs) in C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\Layer.cs:line 244
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.Queue`1..ctor(IEnumerable`1 collection)
   at Aurora.Profiles.LightEvent.UpdateLights(EffectFrame frame) in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\LightEvent.cs:line 65
   at Aurora.Profiles.LightingStateManager.Update() in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\LightingStateManager.cs:line 638
   at Aurora.Profiles.LightingStateManager.<InitUpdate>b__77_0(Object g) in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\LightingStateManager.cs:line 507

**Comment by ShawnTheShadow** [comment] 2019-11-24 23:55
I can confirm this issue as well, i debugged it came up to line 285 in GameEvent_EliteDangerous.cs saying the key has already been added. `                    
if (bind.mappings.Any())
{
    commandToBind.Add(command.Name, bind);//error occurs here, key already been added
    bindToCommand.Add(bind, command.Name);
}`

**Comment by DrParanoia** [comment] 2019-12-03 17:59
Are there any steps to reproduce? Maybe there are some key binds that are causing this?

**Comment by TomW1605** [comment] 2019-12-15 00:55
@KaHonu & @ShawnTheShadow could you please both attach your key binds so we can test and see if there are spesific binds that might cause this?

**Comment by ShawnTheShadow** [comment] 2019-12-15 01:13
[Custom.3.0.zip](https://github.com/DrParanoia/Aurora/files/3964524/Custom.3.0.zip)

**Comment by TomW1605** [comment] 2019-12-15 01:32
Thanks, I will do some testing however because you use a Thrustmeter HOTAS that I don’t have I will have to modify it so I can test it. Hopefully this doesn’t cause any issues (or at least doesn’t fix any) as Aurora should not care about those bindings.

On the other hand, it might be the Thrustmeter causing the issue but we will need to wait for @KaHonu to send his so I can compare and see if there is any common ground that might be the issue.

**Comment by ShawnTheShadow** [comment] 2019-12-15 01:42
the keybindings are more or less default with a few changes to the hotas side, it doesnt have enough buttons so keyboard still is needed, although i couldnt see any reason for that error to appear

**Comment by TomW1605** [comment] 2019-12-15 03:50
ok i have tested the modifyed bindings but couldent reproduce the issue. the test file i used was your file with the `ThrustMasterTFlightHOTASX` entries removed using the regex replace: `Device="ThrustMasterTFlightHOTASX" Key=".*"` -> `Device="{NoDevice}" Key=""`

i have attached the test file, could you please test with this file and see if the error is still present with the modifyed file.

[test.3.0.zip](https://github.com/DrParanoia/Aurora/files/3964578/test.3.0.zip)

**Comment by DrParanoia** [comment] 2019-12-20 07:05
@TomW1605 You should leave the file as is. Even if you don't have the HOTAS, it doesn't mean that you can't launch the game without it. Most likely these binds are the issue, since judging by the report, there is a crash when duplicate binds are set (which could be the case with axis I guess). Thanks for testing! I will try to do some testing with these files also.

**Comment by TomW1605** [comment] 2019-12-20 07:21
i did try without changing the file however ED just dident show it in the list because the devices were not there

**Comment by KaHonu** [comment] 2019-12-20 16:36
I have the T16000M HOTAS but everything is working fine for me now. At some point in time I reset my control bindings and I cant seem to reproduce the problem. While experimenting a bit I also noticed that the animation effects don't work initially unless I Alt-Tab out of Elite and then Alt-Tab back in.

**Comment by DrParanoia** [comment] 2020-01-04 14:06
Should be fixed if it was related to what I think it was :D

**Closed as completed by DrParanoia** 2020-01-04 14:06 UTC
Labels: bug
