### ISSUE TITLE
Hyperspace effect doesnt work (on Steelseries M800)

### ISSUE THREAD

**Issue by wulfzbane** [DrParanoia/Aurora#12] opened 2020-01-05 21:24 UTC
### Expected Behaviour
When carrying out a hyperspace jump the keyboard doesn't carry out the RGB sequence. All other parts of the profile appear to be working correctly

### Actual Behaviour
Nothing happens

### Frequency
Everytime

### Aurora Version:
Latest version 0.7

### Previously an Issue?
I tried on the 0.6.4 version and this behaved the same

**Comment by DrParanoia** [comment] 2020-01-06 18:38
Okay, the issue was that the profile did not switch to a newer Journal file if it was created when the game is running. This is easily fixed by Alt+Tabbing out of the game once. The issue is fixed in the new build though ;)

**Closed as completed by DrParanoia** 2020-01-06 18:38 UTC
Labels: bug
